#!/bin/bash

WORKTREE=/var/www/node_proj/xjtu-msc-bot
CONFIG=package.json


while read oldrev newrev ref # post-receive 将读取这三个变量
do
    if [[ $ref =~ .*/master$ ]]; # 仅允许master分支进行部署
    then
        echo "Pull to worktree..."
        #echo "$oldrev $newrev"
        cd $WORKTREE
        unset GIT_DIR
        git pull origin master &> /dev/null\
        git diff --quiet $oldrev $newrev -- $CONFIG
        if [ "$?" -eq "1" ]
        then
            echo "package.json changed"
            echo "install packages..."
            npm install
        else
            echo "package.json does not changed"
        fi
        forever restart app.js
        echo "deployment complete!"
    else
        echo "This is not master branch, and it will not be deployed"
    fi
done
